# Generated by Django 4.2.7 on 2023-12-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_next_door_api', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='files/images'),
        ),
    ]
