# Generated by Django 4.2.7 on 2023-12-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_next_door_api', '0006_alter_vendor_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
