# Generated by Django 4.2.7 on 2023-12-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_next_door_api', '0007_rename_enddate_market_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='market',
        ),
        migrations.AddField(
            model_name='vendor',
            name='market',
            field=models.ManyToManyField(null=True, to='market_next_door_api.market'),
        ),
    ]
