# Generated by Django 4.2.7 on 2023-12-05 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_next_door_api', '0008_alter_customer_location_alter_customer_phone'),
        ('market_next_door_api', '0008_vendor_phone_alter_item_size_remove_vendor_market_and_more'),
    ]

    operations = [
    ]
