# Generated by Django 4.2.7 on 2023-12-05 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_next_door_api', '0009_merge_20231205_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='market',
        ),
        migrations.AddField(
            model_name='vendor',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market_next_door_api.market'),
        ),
    ]
