# Generated by Django 4.2.7 on 2023-12-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_next_door_api', '0010_remove_vendor_market_vendor_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder',
            name='item',
        ),
        migrations.AddField(
            model_name='preorder',
            name='items',
            field=models.ManyToManyField(to='market_next_door_api.item'),
        ),
        migrations.DeleteModel(
            name='PreorderItem',
        ),
    ]
