# Generated by Django 4.2.7 on 2023-12-05 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_next_door_api', '0012_preorder_quantity_of_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preorder',
            old_name='quantity_of_item',
            new_name='quantity_requested',
        ),
        migrations.RemoveField(
            model_name='preorder',
            name='items',
        ),
        migrations.AddField(
            model_name='preorder',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market_next_door_api.item'),
            preserve_default=False,
        ),
    ]
