# Generated by Django 4.2.7 on 2023-12-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_next_door_api', '0002_customer_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
