# Generated by Django 4.2.7 on 2023-12-02 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_next_door_api', '0005_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market_next_door_api.market'),
        ),
    ]
